geekshop/admins/urls.py
from django.contrib import admin
from django.urls import path
from admins.views import index

from admins.views import UsersListViews, UserCreateView, UserUpdateView, UserDeleteView
from admins.views import CategoryListView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView
from admins.views import ProductListView, ProductCreateView, ProductUpdateView, ProductDeleteView

app_name = 'admins'

urlpatterns = [
    path('', index, name='index'),
    path('users/', UsersListViews.as_view(), name='admin_users'),
    path('users-create/', UserCreateView.as_view(), name='admin_users_create'),
    path('users-update/<int:pk>', UserUpdateView.as_view(), name='admin_users_update'),
    path('users-delete/<int:pk>', UserDeleteView.as_view(), name='admin_users_delete'),

    path('category/', CategoryListView.as_view(), name='admin_category'),
    path('category/create/', CategoryCreateView.as_view(), name='admin_category_create'),
    path('category-update/<int:pk>', CategoryUpdateView.as_view(), name='admin_category_update'),
    path('category-delete/<int:pk>', CategoryDeleteView.as_view(), name='admin_category_delete'),

    path('products/read/', ProductListView.as_view(), name='products_read'),
    path('products/create/category/', ProductCreateView.as_view(), name='product_create', ),
    # path('products/read/category/<int:pk>/', products, name='products'),
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from mainapp.views import index #, contact
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import cache_control
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('', index, name='index'),
    path('products/',  include('mainapp.urls', namespace='mainapp')),
    # path('contact/', contact,),
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# для того чтобы статика не кешировалась использовать при runserver --nostatic
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, view=cache_control(no_cache=True, must_revalidate=True)(serve))
# другой способ не кэшировать
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, view=never_cache(serve))

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

geekshop/admins/templates/admins/admin-category-create.html
{% extends 'admins/base.html' %}

{% block content %}
            <div class="container-fluid">
                <h1 class="mt-4">{{title}}</h1>

            {% if error_mess %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert"
                     style="margin-top: 50px;">
                    <strong>Holy guacamole!</strong>

                        {{ error_mess | escape }}

                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}

                <form action="{% url 'admins:admin_category_create' %}" method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Наименование</label>
                                {{ form.name }}
                            </div>
                        </div>

                    </div>
                    <div class="form-row">

                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                                {{ form.description }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
{% endblock %}

geekshop/admins/templates/admins/admin-category-read.html
{% extends 'admins/base.html' %}
{% load static %}

{% block content%}
    <div class="container-fluid">
        <h1 class="mt-4">{{title}}</h1>



        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Категории
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Наименование</th>
                            <th>Описание</th>
                            <th>Активный</th>
                            <th>Удалить</th>
                            <th>Изменить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Наименование</th>
                            <th>Описание</th>
                            <th>Активный</th>
                            <th>Удалить</th>
                            <th>Изменить</th>
                        </tr>
                        </tfoot>
                        <tbody>

                        {% for category in object_list %}
                            <tr>
                                <td>{{ category.name }}</td>
                                <td>{{ category.description }}</td>
                                <td class="text-center">
                                    {% if category.is_active %}
                                        <i class="fas fa-check-circle"></i>
                                    {% else %}
                                        <i class="fas fa-times-circle"></i>
                                    {% endif %}
                                </td>

                                <td>
                                    <a href="{% url 'admins:admin_category_update' category.id %}">
                                        <input class="btn btn-success btn-block" type="submit" value="Изменить">
                                    </a>
                                </td>

                                <td>
                                    <form action="{% url 'admins:admin_category_delete' category.id %}" method="post">
                                        {% csrf_token %}
                                        <input class="btn btn-danger btn-block" type="submit" value="Деактивировать / Активировать">
                                    </form>
                                </td>

                            </tr>

                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'admins:admin_category_create' %}">
                    <button class="btn btn-success">Создать категорию</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin-category-update.html
{% extends 'admins/base.html' %}

{% block content %}
            <div class="container-fluid">
                <h1 class="mt-4">{{title}}</h1>
                <form action="{% url 'admins:admin_category_update' productcategory.id %}" method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Наименование</label>
                                {{ form.name }}
                            </div>
                        </div>

                    </div>
                    <div class="form-row">

                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                                {{ form.description }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
{% endblock %}

geekshop/admins/templates/admins/admin-product-create.html
{% extends 'admins/base.html' %}

{% block content %}
            <div class="container-fluid">
                <h1 class="mt-4">{{title}}</h1>



            {% if error_mess %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert"
                     style="margin-top: 50px;">
                    <strong>Holy guacamole!</strong>

                        {{ error_mess | escape }}

                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}

                <form action="{% url 'admins:product_create' %}" method="post">
                    {% csrf_token %}

                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ product_form.category.id_for_label }}">категория</label>
                                {{ form.category }}
                            </div>
                        </div>
                    </div>


                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ product_form.name.id_for_label }}">Наименование</label>
                                {{ form.name }}
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ product_form.description.id_for_label }}">Описание</label>
                                {{ form.description }}
                            </div>
                        </div>
                    </div>


                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ product_form.price.id_for_label }}">Цена</label>
                                {{ form.price }}
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ product_form.quantity.id_for_label }}">Количество</label>
                                {{ form.quantity }}
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ product_form.image.id_for_label }}">Выберите изображение</label>
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-lg-6" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>

                </form>
            </div>
{% endblock %}

geekshop/admins/templates/admins/admin-product-read.html
{% extends 'admins/base.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid">
        <h1 class="mt-4">{{ title }}</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Продукты
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Наименование</th>
                            <th>Описание</th>
                            <th>Категория</th>
                            <th>Цена</th>
                            <th>Количество</th>
                            <th>Активный</th>
                            <th>Удалить</th>
                            <th>Изменить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Наименование</th>
                            <th>Описание</th>
                            <th>Категория</th>
                            <th>Цена</th>
                            <th>Количество</th>
                            <th>Активный</th>
                            <th>Удалить</th>
                            <th>Изменить</th>
                        </tr>
                        </tfoot>
                        <tbody>

                        {% for product in object_list %}
                            <tr>
                                <td>{{ product.name }}</td>
                                <td>{{ product.description }}</td>
                                 <td>{{ product.category }}</td>
                                 <td>{{ product.price }}</td>
                                 <td>{{ product.quantity }}</td>

                                <td class="text-center">
                                    {% if product.is_active %}
                                        <i class="fas fa-check-circle"></i>
                                    {% else %}
                                        <i class="fas fa-times-circle"></i>
                                    {% endif %}
                                </td>

                                <td>
                                    <form action="{% url 'admins:product_update' product.id %}">
                                        {% csrf_token %}
                                        <input class="btn btn-success btn-block" type="submit" value="Изменить">
                                    </form>
                                </td>

                                <td>
                                    <form action="{% url 'admins:product_delete' product.id %}"
                                          method="post">
                                        {% csrf_token %}
                                        <input class="btn btn-danger btn-block" type="submit" value="Деактивировать/ Активировать">
                                    </form>
                                </td>

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="card-footer">
                <a href="{% url 'admins:product_create' %}" >
                    <button class="btn btn-success" >Создать товар </button>
                </a>
            </div>


        </div>
    </div>


{% endblock %}

geekshop/admins/templates/admins/admin-users-create.html
{% extends 'admins/base.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid">
        <h1 class="mt-4">Создание пользователя</h1>



        {% if error_mess %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert"
             style="margin-top: 50px;">
            <strong>Holy guacamole!</strong>

                {{ error_mess | escape }}

            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif %}

        <form action="{% url 'admins:admin_users_create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{form.first_name.id_for_label}}">Имя</label>
                        {{ form.first_name}}
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{form.last_name.id_for_label}}">Фамилия</label>
                        {{ form.last_name }}
                    </div>
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="col-lg-12">
                    <div class="custom-file">
                        {{ form.avatar }}
                        <label class="custom-file-label" for="{{form.avatar.id_for_label}}">Выберите изображение</label>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-5">
                    <label class="small mb-1" for="{{form.username.id_for_label}}">Имя пользователя</label>
                    {{ form.username }}
                </div>
                <div class="col-lg-5">
                    <label class="small mb-1" for="{{form.email.id_for_label}}">Адрес электронной
                        почты</label>
                    {{ form.email }}
                </div>
                <div class="col-lg-2">
                    <label class="small mb-1" for="{{ form.age.id_for_label }}">Возраст</label>
                    {{ form.age }}
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{form.password1.id_for_label }}">Пароль</label>
                    {{ form.password1 }}
                </div>
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{form.password2.id_for_label}}">Повторите пароль</label>
                    {{ form.password2}}
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-12" style="margin-top: 33px;">
                    <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                </div>
            </div>
        </form>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin-users-read.html
{% extends 'admins/base.html' %}
{% load static %}

{% block content%}
    <div class="container-fluid">
        <h1 class="mt-4">Пользователи</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Пользователи
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                        </tr>
                        </tfoot>
                        <tbody>

                        {% for user in object_list %}
                            <tr>
                                <td><a href="{% url 'admins:admin_users_update' user.id %}" style="color: dodgerblue">{{ user.username }}</a></td>
                                <td>{{ user.first_name }}</td>
                                <td>{{user.last_name }}</td>
                                <td>{{ user.email }}</td>

                                <td class="text-center">
                                    {% if user.is_staff %}
                                        <i class="fas fa-check-circle"></i>
                                    {% else %}
                                        <i class="fas fa-times-circle"></i>
                                    {% endif %}
                                </td>

                                <td class="text-center">
                                    {% if user.is_active %}
                                        <i class="fas fa-check-circle"></i>
                                    {% else %}
                                        <i class="fas fa-times-circle"></i>
                                    {% endif %}
                                </td>

                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'admins:admin_users_create' %}">
                    <button class="btn btn-success">Создать пользователя</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin-users-update-delete.html
{% extends 'admins/base.html' %}
{% load static %}

{% block content%}
    <div class="container-fluid">
        <h1 class="mt-4">Редактирование пользователя | {{ user.username }}</h1>
        <div class="card-body">
            <form action="{% url 'admins:admin_users_update' user.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{form.first_name.id_for_label}}">Имя</label>
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{form.last_name.id_for_label}}">Фамилия</label>
                            {{ form.last_name}}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            {{form.avatar}}
                            <label class="custom-file-label" for="{{form.avatar.id_for_label}}">Выберите изображение</label>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{form.username.id_for_label}}">Имя пользователя</label>
                        {{form.username}}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{form.email.id_for_label}}">Адрес электронной
                            почты</label>
                        {{form.email}}
                    </div>
                    <div class="col-lg-2">
                        <label class="small mb-1" for="{{ form.age.id_for_label }}">Возраст</label>
                        {{ form.age }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
            <form action="{% url 'admins:admin_users_delete' user.id %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-danger btn-block" type="submit" value="Деактивировать / Активировать">
                    </div>
                </div>
            </form>

        </div>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin.html
{% extends 'admins/base.html' %}
{% load static %}

{% block content%}
    <div class="container-fluid">
        <h1 class="mt-4">Административная панель</h1>
    </div>
{% endblock%}

geekshop/admins/templates/admins/product-update.html
{% extends 'admins/base.html' %}

{% block content %}
            <div class="container-fluid">
                <h1 class="mt-4">{{title}}</h1>
                <form action="{% url 'admins:product_update' product.id %}" method="post">
                    {% csrf_token %}

                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ update_form.name.id_for_label }}">Наименование</label>
                                {{ form.name }}
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ update_form.category.id_for_label }}">категория</label>
                                {{ form.category }}
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ update_form.description.id_for_label }}">Описание</label>
                                {{ form.description }}
                            </div>
                        </div>
                    </div>


                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ update_form.price.id_for_label }}">Цена</label>
                                {{ form.price }}
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ update_form.quantity.id_for_label }}">Количество</label>
                                {{ form.quantity }}
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ update_form.image.id_for_label }}">Выберите изображение</label>
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-lg-3" style="margin-top: 33px;">
                            <input class="btn float-lg-right btn-info btn-block btn-lg" type="submit" value="Сохранить">
                        </div>
                        <div class="col-lg-3" style="margin-top: 33px;">
                            <input type="button" class="btn float-lg-right btn-danger btn-block btn-lg"
                                   onclick="window.location.href = '{% url 'admins:products_read' %}';"
                                   value="Отмена"/>
                        </div>
                    </div>
                </form>
            </div>
{% endblock %}